---
- name: Ensures gophish dir exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ gophish_dir }}'
  - '{{ gophish_dir }}/data'

- name: gophish container
  docker_container:
    name: "{{ gophish_container_name }}"
    image: "{{ gophish_docker_image }}"
    state: started
    hostname: "{{ gophish_hostname }}"
    restart_policy: unless-stopped
    ports: "{{ gophish_ports }}"
    volumes:
      - "{{ gophish_dir }}/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: "{{ gophish_docker_network }}"
    purge_networks: true
  notify:
    - restart gophish